theme: jekyll-theme-hacker
title: McCaffrey 2022
description: McCaffrey 2022
sass:
    load_paths:
        - _scss
        - node_modules/bootstrap
plugins:
    - jekyll-redirect-from
exclude: ["node_modules", "vendor"]
include: [".nojekyll"]
github: [metadata]
google_analytics: UA-41775478-2
repository: labsyspharm/cycif.org
speech_bucket: www.cycif.org
